# Generated by Django 4.2.6 on 2023-12-15 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveCodeCreateRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createrIP', models.CharField(max_length=20, null=True)),
                ('receiveCode', models.CharField(max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveCodeTempStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiveCode', models.CharField(max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveCodeAccessRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accessIP', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ReceiveCodeCreateRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webrtc.receivecodecreaterecord')),
            ],
        ),
    ]
