# Generated by Django 4.2.6 on 2023-12-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrtc', '0002_receivecodeaccessrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivecodeaccessrecord',
            name='receiveCode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
