# Generated by Django 4.2.1 on 2023-06-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileupload", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file", name="filesize", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="file",
            name="filetype",
            field=models.CharField(default=".docx", max_length=255),
        ),
    ]
