# Generated by Django 4.2.1 on 2023-06-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileupload", "0002_file_filesize_file_filetype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file", name="filesize", field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="file",
            name="filetype",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
