# Generated by Django 4.2.1 on 2023-06-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileupload", "0004_file_receivecode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="receiveCode",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
