# Generated by Django 4.2.6 on 2023-11-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0005_alter_file_receivecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveCodeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiveCode', models.CharField(max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
