# Generated by Django 4.2.6 on 2023-11-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0006_receivecoderecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceiveCodeRecord',
        ),
    ]
